db_ipaddress = "114.212.190.189"
db_username = "xxwang"
db_password = "xxwang"
db_dbname = "dataset_search_2018nov"
dataset_path = 'D:/Study_Work/NJU/System/20191015Datasets/data_gov_datasets'
# index_path = 'D:/Study_Work/NJU/System/DB_Index_backup'
# store_path = 'D:/Study_Work/NJU/System/DB_Index'
index_path = '/Users/liziyang/Myself/tmp_DB/'
store_path = '/Users/liziyang/Myself/tmp_DB/'
info_file = './Confs/database.json'